
var spelling = [

{
"head": "animals",
"one": "../images/goat.jpg",
"one0": "goat",
"two": "../images/cow.jpg",
"two0": "cow",
"three": "../images/cat.jpg",
"three0": "cat",
"four": "../images/lion.jpg",
"four0": "lion",
"five": "../images/tiger.jpg",
"five0": "tiger",
"six":  "../images/dog.jpeg",
"six0":  "dog",
"seven": "../images/mouse.jpg",
"seven0":  "mouse",
"eight": "../images/pig.jpeg",
"eight0": "pig",
"nine":  "../images/frog.jpg",
"nine0": "frog",
"ten":  "../images/fish.jpg",
"ten0": "fish",
"next": "../images/44.jpeg",
"back": "../images/46.jpg",
},
{
"head": "clothings",
"one": "../images/coat.jpg",
"one0": "coat",
"two": "../images/dress.jpg",
"two0": "dress",
"three": "../images/headset.jpg",
"three0": "headset",
"four": "../images/towel.jpg",
"four0": "towel",
"five": "../images/jacket.jpg",
"five0": "jacket",
"six":  "../images/shirt.jpg",
"six0":  "shirt",
"seven": "../images/shoe.jpg",
"seven0":  "shoe",
"eight": "../images/skirt.jpg",
"eight0": "skirt",
"nine":  "../images/sweater.jpg",
"nine0": "sweater",
"ten":  "../images/trousers.jpg",
"ten0": "trousers",
"next": "../images/44.jpeg",
"back": "../images/46.jpg",
},

{
"head": "accessories",
"one": "../images/bracelet.jpg",
"one0": "bracelet",
"two": "../images/cap.jpg",
"two0": "cap",
"three": "../images/couflings.jpg",
"three0": "couflings",
"four": "../images/earring.jpg",
"four0": "earrings",
"five": "../images/glasses.jpg",
"five0": "glasses",
"six":  "../images/purse.jpg",
"six0":  "purse",
"seven": "../images/ring.jpg",
"seven0":  "ring",
"eight": "../images/shoelace.jpg",
"eight0": "shoelace",
"nine":  "../images/tie.jpg",
"nine0": "tie",
"ten":  "../images/bag.jpg",
"ten0": "bag",
"next": "../images/44.jpeg",
"back": "../images/46.jpg",
},

{
"head": "vehicles",
"one": "../images/airplane.jpg",
"one0": "airplane",
"two": "../images/bicycle.jpg",
"two0": "bicycle",
"three": "../images/bus.jpg",
"three0": "bus",
"four": "../images/car.jpg",
"four0": "car",
"five": "../images/helicopter.jpg",
"five0": "helicopter",
"six":  "../images/tractor.jpg",
"six0":  "tractor",
"seven": "../images/tricycle.jpg",
"seven0":  "tricycle",
"eight": "../images/van.jpg",
"eight0": "van",
"nine":  "../images/lorry.jpg",
"nine0": "lorry",
"ten":  "../images/train.jpg",
"ten0": "train",
"next": "../images/44.jpeg",
"back": "../images/46.jpg",
},

{
"head": "gadget",
"one": "../images/camera.jpg",
"one0": "camera",
"two": "../images/phone.jpg",
"two0": "phone",
"three": "../images/computer.jpg",
"three0": "computer",
"four": "../images/watch.jpg",
"four0": "watch",
"five": "../images/tablets.jpg",
"five0": "tablets",
"six":  "../images/television.jpg",
"six0":  "television",
"seven": "../images/projector.jpg",
"seven0":  "projector",
"eight": "../images/microphone.jpg",
"eight0": "microphone",
"nine":  "../images/headset.jpg",
"nine0": "headset",
"ten":  "../images/wallet.jpg",
"ten0": "wallet",
"next": "../images/44.jpeg",
"back": "../images/46.jpg",
},
{
"head": "human body",
"one": "../images/teeth.jpg",
"one0": "teeth",
"two": "../images/mouth.jpg",
"two0": "mouth",
"three": "../images/nose.png",
"three0": "nose",
"four": "../images/leg.png",
"four0": "leg",
"five": "../images/head.jpg",
"five0": "head",
"six":  "../images/eye.jpg",
"six0":  "eye",
"seven": "../images/ear.jpg",
"seven0":  "ear",
"eight": "../images/chest.jpg",
"eight0": "chest",
"nine":  "../images/back.jpg",
"nine0": "back",
"ten":  "../images/hand.png",
"ten0": "hand",
"next": "../images/44.jpeg",
"back": "../images/46.jpg",
},

{
"head": "universe",
"one": "../images/cloud.jpg",
"one0": "cloud",
"two": "../images/earth.jpg",
"two0": "earth",
"three": "../images/moon.jpg",
"three0": "moon",
"four": "../images/planet.jpg",
"four0": "planet",
"five": "../images/space.jpg",
"five0": "space",
"six":  "../images/stars.jpg",
"six0":  "stars",
"seven": "../images/sun.jpg",
"seven0":  "sun",
"eight": "../images/sky.jpg",
"eight0": "sky",
"nine":  "../images/universe.jpg",
"nine0": "universe",
"ten":  "../images/rain.jpg",
"ten0": "rain",
"next": "../images/44.jpeg",
"back": "../images/46.jpg",
},

{
"head": "nature",
"one": "../images/desert.jpg",
"one0": "desert",
"two": "../images/field.jpeg",
"two0": "field",
"three": "../images/glacier.jpg",
"three0": "glacier",
"four": "../images/forest.jpg",
"four0": "forest",
"five": "../images/cave.jpg",
"five0": "cave",
"six":  "../images/hill.jpg",
"six0":  "hill",
"seven": "../images/pit.jpg",
"seven0":  "pit",
"eight": "../images/rainbow.jpg",
"eight0": "rainbow",
"nine":  "../images/rock.jpeg",
"nine0": "rock",
"ten":  "../images/valley.jpg",
"ten0": "valley",
"next": "../images/44.jpeg",
"back": "../images/46.jpg",
},


]
