
var spelling = [

{
"one": "1",
"one0": "one",
"two": "2",
"two0": "two",
"three": "3",
"three0": "three",
"four": "4",
"four0": "four",
"five": "5",
"five0": "five",
"six":  "6",
"six0":  "six",
"seven": "7",
"seven0":  "seven",
"eight": "8",
"eight0": "eight",
"nine":  "9",
"nine0": "nine",
"ten":  "10",
"ten0": "ten",
"next": "../images/44.jpeg",
"back": "../images/46.jpg",
},
{
"one": "11",
"one0": "eleven",
"two": "12",
"two0": "twelve",
"three": "13",
"three0": "thirteen",
"four": "14",
"four0": "fourteen",
"five": "15",
"five0": "fifteen",
"six":  "16",
"six0":  "sixteen",
"seven": "17",
"seven0":  "seventeen",
"eight": "18",
"eight0": "eighteen",
"nine":  "19",
"nine0": "nineteen",
"ten":  "20",
"ten0": "twenty",
"next": "../images/44.jpeg",
"back": "../images/46.jpg",
},

{
"one": "21",
"one0": "twenty - one",
"two": "22",
"two0": "twenty - two",
"three": "23",
"three0": "twenty - three",
"four": "24",
"four0": "twenty - four",
"five": "25",
"five0": "twenty - five",
"six":  "26",
"six0":  "twenty - six",
"seven": "27",
"seven0":  "twenty - seven",
"eight": "28",
"eight0": "twenty - eight",
"nine":  "29",
"nine0": "twenty - nine",
"ten":  "30",
"ten0": "thirty",
"next": "../images/44.jpeg",
"back": "../images/46.jpg",
},

{
"one": "31",
"one0": "thirty - one",
"two": "32",
"two0": "thirty - two",
"three": "33",
"three0": "thirty - three",
"four": "34",
"four0": "thirty - four",
"five": "35",
"five0": "thirty - five",
"six":  "36",
"six0":  "thirty - six",
"seven": "37",
"seven0":  "thirty - seven",
"eight": "38",
"eight0": "thirty - eight",
"nine":  "39",
"nine0": "thirty - nine",
"ten":  "40",
"ten0": "forty",
"next": "../images/44.jpeg",
"back": "../images/46.jpg",
},

{
"one": "41",
"one0": "forty - one",
"two": "42",
"two0": "forty - two",
"three": "43",
"three0": "forty - three",
"four": "44",
"four0": "forty - four",
"five": "45",
"five0": "forty - five",
"six":  "46",
"six0":  "forty - six",
"seven": "47",
"seven0":  "forty - seven",
"eight": "48",
"eight0": "forty - eight",
"nine":  "49",
"nine0": "forty - nine",
"ten":  "50",
"ten0": "fifty",
"next": "../images/44.jpeg",
"back": "../images/46.jpg",
},
{
"one": "51",
"one0": "fifty - one",
"two": "52",
"two0": "fifty - two",
"three": "53",
"three0": "fifty - three",
"four": "54",
"four0": "fifty - four",
"five": "55",
"five0": "fifty - five",
"six":  "56",
"six0":  "fifty - six",
"seven": "57",
"seven0":  "fifty - seven",
"eight": "58",
"eight0": "fifty - eight",
"nine":  "59",
"nine0": "fifty - nine",
"ten":  "60",
"ten0": "sixty",
"next": "../images/44.jpeg",
"back": "../images/46.jpg",
},
{
"one": "61",
"one0": "sixty - one",
"two": "62",
"two0": "sixty - two",
"three": "63",
"three0": "sixty - three",
"four": "64",
"four0": "sixty - four",
"five": "65",
"five0": "sixty - five",
"six":  "66",
"six0":  "sixty - six",
"seven": "67",
"seven0":  "sixty - seven",
"eight": "68",
"eight0": "sixty - eight",
"nine":  "69",
"nine0": "sixty - nine",
"ten":  "70",
"ten0": "seventy",
"next": "../images/44.jpeg",
"back": "../images/46.jpg",
},
{
"one": "71",
"one0": "seventy - one",
"two": "72",
"two0": "seventy - two",
"three": "73",
"three0": "seventy - three",
"four": "74",
"four0": "seventy - four",
"five": "75",
"five0": "seventy - five",
"six":  "76",
"six0":  "seventy - six",
"seven": "77",
"seven0":  "seventy - seven",
"eight": "78",
"eight0": "seventy - eight",
"nine":  "79",
"nine0": "seventy - nine",
"ten":  "80",
"ten0": "eighty",
"next": "../images/44.jpeg",
"back": "../images/46.jpg",
},
{
"one": "81",
"one0": "eighty - one",
"two": "82",
"two0": "eighty - two",
"three": "83",
"three0": "eighty - three",
"four": "84",
"four0": "eighty - four",
"five": "85",
"five0": "eighty - five",
"six":  "86",
"six0":  "eighty - six",
"seven": "87",
"seven0":  "eighty - seven",
"eight": "88",
"eight0": "eighty - eight",
"nine":  "89",
"nine0": "eighty - nine",
"ten":  "90",
"ten0": "ninety",
"next": "../images/44.jpeg",
"back": "../images/46.jpg",
},

{
"one": "91",
"one0": "ninety - one",
"two": "92",
"two0": "ninety - two",
"three": "93",
"three0": "ninety - three",
"four": "94",
"four0": "ninety - four",
"five": "95",
"five0": "ninety - five",
"six":  "96",
"six0":  "ninety - six",
"seven": "97",
"seven0":  "ninety - seven",
"eight": "98",
"eight0": "ninety - eight",
"nine":  "99",
"nine0": "ninety - nine",
"ten":  "100",
"ten0": "one hundred",
"next": "../images/44.jpeg",
"back": "../images/46.jpg",
},
]
